# -*- coding: utf-8 -*-
"""Basic Movie Recommender System.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hG7xi7duSuN6hVrTidOvfAqv02DP6GVs

https://colab.research.google.com/

Data Download Link: https://files.grouplens.org/datasets/movielens/ml-latest-small.zip

Data Source: https://grouplens.org/datasets/movielens/latest/
"""

'''
@article{10.1145/2827872,
author = {Harper, F. Maxwell and Konstan, Joseph A.},
title = {The MovieLens Datasets: History and Context},
year = {2015},
issue_date = {January 2016},
publisher = {Association for Computing Machinery},
address = {New York, NY, USA},
volume = {5},
number = {4},
issn = {2160-6455},
url = {https://doi.org/10.1145/2827872},
doi = {10.1145/2827872},
journal = {ACM Trans. Interact. Intell. Syst.},
month = dec,
articleno = {19},
numpages = {19},
keywords = {Datasets, recommendations, ratings, MovieLens}
}
'''

import pandas

ratings_features = ["user_id", "item_id", "rating", "timestamp"]

ratings_dataframe = pandas.read_csv("ratings.csv",
                                    names = ratings_features)

ratings_dataframe

FIRST_INDEX_ROW = 0

ratings_dataframe = ratings_dataframe.drop(ratings_dataframe.index[FIRST_INDEX_ROW])

ratings_dataframe

ratings_dataframe.info()

ratings_dataframe = ratings_dataframe.astype("float")

ratings_dataframe.info()

ratings_dataframe

movies_dataframe = pandas.read_csv("movies.csv")

movies_dataframe

movies_dataframe.info()

