# -*- coding: utf-8 -*-
"""Movie Recommender with Machine Learning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/106Gtd93VDK9_4Xsrn43Wz0xjL47bQpMa

https://colab.research.google.com/

Data Download Link: https://files.grouplens.org/datasets/movielens/ml-latest-small.zip

Data Source: https://grouplens.org/datasets/movielens/latest/
"""

'''
@article{10.1145/2827872,
author = {Harper, F. Maxwell and Konstan, Joseph A.},
title = {The MovieLens Datasets: History and Context},
year = {2015},
issue_date = {January 2016},
publisher = {Association for Computing Machinery},
address = {New York, NY, USA},
volume = {5},
number = {4},
issn = {2160-6455},
url = {https://doi.org/10.1145/2827872},
doi = {10.1145/2827872},
journal = {ACM Trans. Interact. Intell. Syst.},
month = dec,
articleno = {19},
numpages = {19},
keywords = {Datasets, recommendations, ratings, MovieLens}
}
'''

import pandas

movies_dataframe = pandas.read_csv("movies.csv")

movies_dataframe

movies_dataframe.set_index("movieId", inplace = True)

movies_dataframe

ratings_dataframe = pandas.read_csv("ratings.csv")

ratings_dataframe

total_counts = ratings_dataframe["movieId"].value_counts()

total_counts

movies_dataframe["ratingsCount"] = total_counts

movies_dataframe

SEGMENT_LENGTH = 10

movies_dataframe.sort_values("ratingsCount", ascending = False).head(SEGMENT_LENGTH)

average_ratings = ratings_dataframe.groupby("movieId").mean()["rating"]

average_ratings

movies_dataframe["averageRating"] = average_ratings

movies_dataframe

movies_dataframe.sort_values(["ratingsCount", "averageRating"],
                             ascending = False).head(SEGMENT_LENGTH)

MINIMUM_RATINGS_COUNT = 100

minimum_ratings_subset = movies_dataframe.query(f"ratingsCount >= {MINIMUM_RATINGS_COUNT}").sort_values("ratingsCount")

minimum_ratings_subset

import numpy

USER_1_POSITION_X = 3

USER_1_POSITION_Y = 7.5

USER_2_POSITION_X = 7

USER_2_POSITION_Y = 8

position_user_1 = numpy.array([USER_1_POSITION_X, USER_1_POSITION_Y])

position_user_2 = numpy.array([USER_2_POSITION_X, USER_2_POSITION_Y])

position_user_1

position_user_2

def find_distance_between_users(position_user_1, position_user_2):

  (delta_x, delta_y) = position_user_1 - position_user_2

  return (delta_x ** 2 + delta_y ** 2) ** (1/2)

find_distance_between_users(position_user_1, position_user_2)

def find_user_ratings(userId):
  
  user_ratings = ratings_dataframe.query(f"userId == {userId}")

  return user_ratings[["movieId", "rating"]].set_index("movieId")

ID_OF_USER_1 = 1

ID_OF_USER_2 = 610

user_1_ratings = find_user_ratings(ID_OF_USER_1)

user_1_ratings

user_2_ratings = find_user_ratings(ID_OF_USER_2)

user_2_ratings

ratings_comparison = user_1_ratings.join(user_2_ratings, 
                                         lsuffix="_user1", 
                                         rsuffix="_user2").dropna()

ratings_comparison

user1_compared = ratings_comparison["rating_user1"]

user2_compared = ratings_comparison["rating_user2"]

numpy.linalg.norm(user1_compared - user2_compared)